// <auto-generated />
using System;
using Carely.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carely.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516153702_AddDetectionSession")]
    partial class AddDetectionSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carely.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "super.admin@babycare.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "Admin@123",
                            PhoneNumber = "01000000000",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "mona.admin@babycare.com",
                            FirstName = "Mona",
                            LastName = "Adel",
                            PasswordHash = "Mona@123",
                            PhoneNumber = "01011111111",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "hassan.admin@babycare.com",
                            FirstName = "Hassan",
                            LastName = "Tarek",
                            PasswordHash = "Hassan@123",
                            PhoneNumber = "01022222222",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Carely.Models.Baby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Developmental")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("Babies", (string)null);
                });

            modelBuilder.Entity("Carely.Models.BabyVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BabyId")
                        .HasColumnType("int");

                    b.Property<bool>("Checkbox")
                        .HasColumnType("bit");

                    b.Property<int>("VaccinationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.HasIndex("VaccinationId");

                    b.ToTable("BabyVaccination", (string)null);
                });

            modelBuilder.Entity("Carely.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Clinics", (string)null);
                });

            modelBuilder.Entity("Carely.Models.ClinicWorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicWorkTimes", (string)null);
                });

            modelBuilder.Entity("Carely.Models.DetectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BabyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.ToTable("DetectionSessions", (string)null);
                });

            modelBuilder.Entity("Carely.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Specification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 40,
                            Email = "ahmed.samir@clinic.com",
                            FirstName = "Ahmed",
                            Gender = 0,
                            LastName = "Samir",
                            Link = "bbbb",
                            PasswordHash = "Doctor@123",
                            PhoneNumber = "01033333333",
                            Role = 2,
                            Specification = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            Email = "mariam.magdy@clinic.com",
                            FirstName = "Mariam",
                            Gender = 1,
                            LastName = "Magdy",
                            Link = "gergre",
                            PasswordHash = "Mariam@123",
                            PhoneNumber = "01044444444",
                            Role = 2,
                            Specification = 0
                        });
                });

            modelBuilder.Entity("Carely.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MotherId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("Carely.Models.Lullaby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("LastPosition")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lullabies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 0, 2, 18, 0),
                            FilePath = "audio/lullabies/forest.mp3",
                            Name = "forest lullaby"
                        },
                        new
                        {
                            Id = 2,
                            Duration = new TimeSpan(0, 0, 1, 16, 0),
                            FilePath = "audio/lullabies/sleeping.mp3",
                            Name = "sleeping lullaby"
                        },
                        new
                        {
                            Id = 3,
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            FilePath = "audio/lullabies/silentvoice.mp3",
                            Name = "silentvoice lullaby"
                        });
                });

            modelBuilder.Entity("Carely.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MedicationType")
                        .HasColumnType("int");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Spot")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily vitamin supplement for the baby.",
                            Duration = 30,
                            MedicationType = 2,
                            MotherId = 1,
                            Name = "Vitamin D",
                            Spot = 0,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Taken after meals to relieve cough.",
                            Duration = 10,
                            MedicationType = 2,
                            MotherId = 2,
                            Name = "Cough Syrup",
                            Spot = 0,
                            StartDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prescribed for infection treatment.",
                            Duration = 7,
                            MedicationType = 0,
                            MotherId = 3,
                            Name = "Antibiotic Injection",
                            Spot = 0,
                            StartDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Carely.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MeetingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Meetings", (string)null);
                });

            modelBuilder.Entity("Carely.Models.Mother", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Hight")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mothers", (string)null);
                });

            modelBuilder.Entity("Carely.Models.MotherLullabyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("LastPosition")
                        .HasColumnType("time");

                    b.Property<int>("LullabyId")
                        .HasColumnType("int");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("VolumeLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LullabyId");

                    b.HasIndex("MotherId");

                    b.ToTable("MotherLullabyUsages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPlaying = false,
                            LastPosition = new TimeSpan(0, 0, 0, 30, 0),
                            LullabyId = 1,
                            MotherId = 2,
                            PlayCount = 5,
                            VolumeLevel = 50
                        },
                        new
                        {
                            Id = 2,
                            IsPlaying = false,
                            LastPosition = new TimeSpan(0, 0, 0, 45, 0),
                            LullabyId = 2,
                            MotherId = 3,
                            PlayCount = 3,
                            VolumeLevel = 50
                        },
                        new
                        {
                            Id = 3,
                            IsPlaying = false,
                            LastPosition = new TimeSpan(0, 0, 1, 0, 0),
                            LullabyId = 3,
                            MotherId = 4,
                            PlayCount = 7,
                            VolumeLevel = 50
                        },
                        new
                        {
                            Id = 4,
                            IsPlaying = false,
                            LastPosition = new TimeSpan(0, 0, 0, 20, 0),
                            LullabyId = 1,
                            MotherId = 15,
                            PlayCount = 4,
                            VolumeLevel = 50
                        },
                        new
                        {
                            Id = 5,
                            IsPlaying = false,
                            LastPosition = new TimeSpan(0, 0, 0, 50, 0),
                            LullabyId = 2,
                            MotherId = 16,
                            PlayCount = 6,
                            VolumeLevel = 50
                        });
                });

            modelBuilder.Entity("Carely.Models.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Vaccinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            Disease = "Hepatitis B",
                            Dosage = 0,
                            Name = "Liver B infant"
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            Disease = "Polio",
                            Dosage = 1,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            Disease = "Tuberculosis",
                            Dosage = 2,
                            Name = "BCG"
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Disease = "Polio",
                            Dosage = 3,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            Disease = "Diphtheria, pertussis, tetanus, hepatitis B and influenzae influenzae Hemorrhagic TypeB",
                            Dosage = 3,
                            Name = "The taste of the pentagram"
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            Disease = "Paralyzed polio",
                            Dosage = 3,
                            Name = "Salk's Taste"
                        },
                        new
                        {
                            Id = 7,
                            Age = 4,
                            Disease = "Polio",
                            Dosage = 4,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 8,
                            Age = 4,
                            Disease = "Diphtheria, whooping cough, tetanus, hepatitis B and haemorrhagic influenzae StyleB",
                            Dosage = 4,
                            Name = "The taste of the pentagram"
                        },
                        new
                        {
                            Id = 9,
                            Age = 4,
                            Disease = "Paralyzed polio",
                            Dosage = 4,
                            Name = "Taste of Soulk"
                        },
                        new
                        {
                            Id = 10,
                            Age = 6,
                            Disease = "Polio",
                            Dosage = 5,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 11,
                            Age = 6,
                            Disease = "Diphtheria, pertussis, tetanus, hepatitis B and influenzae influenzae Hemorrhagic TypeB",
                            Dosage = 5,
                            Name = "The taste of the pentagram"
                        },
                        new
                        {
                            Id = 12,
                            Age = 6,
                            Disease = "Paralyzed polio",
                            Dosage = 5,
                            Name = "Taste of Soulk"
                        },
                        new
                        {
                            Id = 13,
                            Age = 9,
                            Disease = "Polio",
                            Dosage = 6,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 14,
                            Age = 12,
                            Disease = "Polio",
                            Dosage = 7,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 15,
                            Age = 12,
                            Disease = "Measles, mumps and rubella",
                            Dosage = 8,
                            Name = "Viral MMR"
                        },
                        new
                        {
                            Id = 16,
                            Age = 18,
                            Disease = "Polio",
                            Dosage = 8,
                            Name = "Sabine"
                        },
                        new
                        {
                            Id = 17,
                            Age = 18,
                            Disease = "Measles, mumps and rubella",
                            Dosage = 8,
                            Name = "Viral MMR"
                        },
                        new
                        {
                            Id = 18,
                            Age = 18,
                            Disease = "Diphtheria, tetanus, and whooping cough",
                            Dosage = 8,
                            Name = "Bacterial triad"
                        });
                });

            modelBuilder.Entity("MeetingMother", b =>
                {
                    b.Property<int>("MeetingsId")
                        .HasColumnType("int");

                    b.Property<int>("MothersId")
                        .HasColumnType("int");

                    b.HasKey("MeetingsId", "MothersId");

                    b.HasIndex("MothersId");

                    b.ToTable("MotherMeetings", (string)null);
                });

            modelBuilder.Entity("Carely.Models.Baby", b =>
                {
                    b.HasOne("Carely.Models.Mother", "Mother")
                        .WithMany("Babies")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carely.Models.BabyVaccination", b =>
                {
                    b.HasOne("Carely.Models.Baby", "Baby")
                        .WithMany("BabyUsage")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carely.Models.Vaccination", "Vaccination")
                        .WithMany("VaccinationUsage")
                        .HasForeignKey("VaccinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baby");

                    b.Navigation("Vaccination");
                });

            modelBuilder.Entity("Carely.Models.Clinic", b =>
                {
                    b.HasOne("Carely.Models.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Carely.Models.ClinicWorkTime", b =>
                {
                    b.HasOne("Carely.Models.Clinic", "Clinic")
                        .WithMany("WorkTimes")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Carely.Models.DetectionSession", b =>
                {
                    b.HasOne("Carely.Models.Baby", "Baby")
                        .WithMany("DetectionSessions")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("Carely.Models.Feedback", b =>
                {
                    b.HasOne("Carely.Models.Meeting", "Meeting")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carely.Models.Mother", "Mother")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carely.Models.Medication", b =>
                {
                    b.HasOne("Carely.Models.Mother", "Mother")
                        .WithMany("Medications")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carely.Models.Meeting", b =>
                {
                    b.HasOne("Carely.Models.Doctor", "Doctor")
                        .WithMany("Meetings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Carely.Models.MotherLullabyUsage", b =>
                {
                    b.HasOne("Carely.Models.Lullaby", "Lullaby")
                        .WithMany("MotherUsages")
                        .HasForeignKey("LullabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carely.Models.Mother", "Mother")
                        .WithMany("LullabyUsages")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lullaby");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MeetingMother", b =>
                {
                    b.HasOne("Carely.Models.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carely.Models.Mother", null)
                        .WithMany()
                        .HasForeignKey("MothersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carely.Models.Baby", b =>
                {
                    b.Navigation("BabyUsage");

                    b.Navigation("DetectionSessions");
                });

            modelBuilder.Entity("Carely.Models.Clinic", b =>
                {
                    b.Navigation("WorkTimes");
                });

            modelBuilder.Entity("Carely.Models.Doctor", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("Carely.Models.Lullaby", b =>
                {
                    b.Navigation("MotherUsages");
                });

            modelBuilder.Entity("Carely.Models.Meeting", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Carely.Models.Mother", b =>
                {
                    b.Navigation("Babies");

                    b.Navigation("Feedbacks");

                    b.Navigation("LullabyUsages");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("Carely.Models.Vaccination", b =>
                {
                    b.Navigation("VaccinationUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
