// <auto-generated />
using System;
using Carely.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carely.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019070624_2nd")]
    partial class _2nd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carely.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "super.admin@babycare.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "Admin@123",
                            PhoneNumber = "01000000000",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "mona.admin@babycare.com",
                            FirstName = "Mona",
                            LastName = "Adel",
                            PasswordHash = "Mona@123",
                            PhoneNumber = "01011111111",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "hassan.admin@babycare.com",
                            FirstName = "Hassan",
                            LastName = "Tarek",
                            PasswordHash = "Hassan@123",
                            PhoneNumber = "01022222222",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Carely.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MedicationType")
                        .HasColumnType("int");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Spot")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily vitamin supplement for the baby.",
                            Duration = 30,
                            MedicationType = 2,
                            MotherId = 1,
                            Name = "Vitamin D",
                            Spot = 0,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Taken after meals to relieve cough.",
                            Duration = 10,
                            MedicationType = 2,
                            MotherId = 2,
                            Name = "Cough Syrup",
                            Spot = 0,
                            StartDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prescribed for infection treatment.",
                            Duration = 7,
                            MedicationType = 0,
                            MotherId = 3,
                            Name = "Antibiotic Injection",
                            Spot = 0,
                            StartDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Carely.Models.Mother", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Hight")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mothers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1998, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            FirstName = "Sara",
                            Hight = 165,
                            LastName = "Khaled",
                            PasswordHash = "123456",
                            PhoneNumber = "01112345678",
                            Role = 0,
                            Weight = 62
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nada@example.com",
                            FirstName = "Nada",
                            Hight = 160,
                            LastName = "Mohsen",
                            PasswordHash = "654321",
                            PhoneNumber = "01098765432",
                            Role = 0,
                            Weight = 58
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eman@example.com",
                            FirstName = "Eman",
                            Hight = 170,
                            LastName = "Ali",
                            PasswordHash = "987654",
                            PhoneNumber = "01234567890",
                            Role = 0,
                            Weight = 70
                        });
                });

            modelBuilder.Entity("Carely.Models.Medication", b =>
                {
                    b.HasOne("Carely.Models.Mother", "Mother")
                        .WithMany("Medications")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carely.Models.Mother", b =>
                {
                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
